"""add sf_lead_id to Lead

Revision ID: 5acfbcce5d8e
Revises: 3fefbfbd5a8a
Create Date: 2025-08-12 10:48:55.815116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5acfbcce5d8e'
down_revision = '3fefbfbd5a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sf_lead_id', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('sf_lead_id')

    # ### end Alembic commands ###
